version: '3.8'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./init-db/data:/tmp/data
    ports:
      - '27018:27017'